name: AutoPlant
version: "5.9"
main: me.theminddroid.autoplant.AutoPlant
api-version: "1.19"
authors: [TheMindDroid]
description: Auto plants crops
depend: [WorldGuard]
commands:
  autoplant:
    description: Allows user to reload the plugin's config file.
    usage: /<command>